---
  - name: Config elk VM with Docker
    hosts: elkservers
    remote_user: Redadmin
    become: true
    tasks: 

    - name: Install docker.io
      apt:
              force_apt_get: yes
              name: docker.io
              state: present

    - name: Install python-pip
      apt:
              force_apt_get: yes
              name: python-pip
              state: present

    - name: Install Docker Module
      pip:
              name: docker
              state: present

    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - name: download and launch a docker web container
      docker_container:
          name: elk
          image: sebp/elk
          state: started
          published_ports:
           - "5601:5601"
           - "9200:9200"
           - "5044:5044"
          restart_policy: always
